import React from "react";
import Head from "next/head";

import "../styles/Home.module.css";

export default function Home() {
  // let name = 'Allan';
  return (
    <div>
      <Head>
        <title>Kurdistan Animals Sanctuary</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      

    </div>
  );
}
